config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/manager_functions'
  get 'employees/sign_in'
  post 'employees/sign_in_employee'
  get 'restaurants/sign_in'
  post 'restaurants/sign_in_restaurant'
  get 'employees/sign_out'
  get 'restaurants/sign_out'
  get '/modification_options/inverse_new'
  post '/modification_options/inverse_create'
  get 'employees/payroll'
  get 'employees/clock_in_out'
  post 'employees/clock'
  get 'items/edit_index'
  post 'sales/destroy_all'
  post 'items/remove_modifications'

  resources :restaurants, only: [:new, :create, :sign_in, :sign_in_restaurant]
  resources :items, except: [:show]
  resources :sale_items, only: [:create, :destroy, :show]
  resources :sales, only: [:update, :index, :destroy, :destroy_all]
  resources :modifications, except: [:show]
  resources :modification_options, only: [:new, :create]
  resources :sale_item_modifications, only: [:new, :create, :destroy]
  resources :employees, except: [:show]

  root 'items#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :restaurant_exists?
  before_action :authenticate
  before_action :must_be_manager, only: [:manager_functions]

  def manager_functions

  end
end

app/views/static_pages/manager_functions.html.erb
<div class="row">
  <div class="columns small-6">
    <span class="radius secondary label">Items</span><br>
    <%= link_to "New Item", new_item_path, class: "button" %>
    <%= link_to "Edit/Delete Item", items_edit_index_path, class: "button" %>
  </div>
  <div class="columns small-6">
    <span class="radius secondary label">Modifications</span><br>
    <%= link_to "New Item Modification", new_modification_path, class: "button green" %>
    <%= link_to "Edit/Delete Modification", modifications_path, class: "button green" %>
    <%= link_to "Modify an item", new_modification_option_path, class: "button green" %>
    <%= link_to "Modify multiple items", modification_options_inverse_new_path, class: "button green" %>
  </div>
</div>

<div class="row">
  <div class="columns small-6">
    <span class="radius secondary label">Employees</span><br>
    <%= link_to "New Employee", new_employee_path, class: "button purple" %>
    <%= link_to "View Employees", employees_path, class: "button purple" %>
  </div>
  <div class="columns small-6">
    <span class="radius secondary label">Other</span><br>
    <%= link_to "Payroll", employees_payroll_path, class: "button magenta" %>
    <%= link_to "Profits", sales_path, class: "button magenta" %>
  </div>
</div>

<div class="row">
  <div class="columns small-12">
    <%= link_to "Back", root_path %>
  </div>
</div>