config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/manager_functions'
  get 'employees/sign_in'
  post 'employees/sign_in_employee'
  get 'restaurants/sign_in'
  post 'restaurants/sign_in_restaurant'
  get 'employees/sign_out'
  get 'restaurants/sign_out'
  get '/modification_options/inverse_new'
  post '/modification_options/inverse_create'
  get 'employees/payroll'
  get 'employees/clock_in_out'
  post 'employees/clock'
  get 'items/edit_index'
  post 'sales/destroy_all'
  post 'items/remove_modifications'

  resources :restaurants, only: [:new, :create, :sign_in, :sign_in_restaurant]
  resources :items, except: [:show]
  resources :sale_items, only: [:create, :destroy, :show]
  resources :sales, only: [:update, :index, :destroy, :destroy_all]
  resources :modifications, except: [:show]
  resources :modification_options, only: [:new, :create]
  resources :sale_item_modifications, only: [:new, :create, :destroy]
  resources :employees, except: [:show]

  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :modification_options
  has_many :modifications, through: :modification_options
  has_many :sale_items
  belongs_to :restaurant

  validates :name,
    presence: true,
    uniqueness: { scope: :restaurant_id }

  validates_presence_of :price
  validates :price,
    numericality: { greater_than: 0, message: "must be greater than $0.00" }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :restaurant_exists?
  before_action :authenticate
  before_action :must_be_manager, only: [:new, :create, :edit, :edit_index, :update, :destroy]

  def index
    @items = current_restaurant.items
    @sale = current_sale
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.price = params[:item][:price].to_f * 100
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @options = @item.modifications
  end

  def edit_index
    @items = current_restaurant.items
  end

  def update
    @item = Item.find(params[:id])
    @options = @item.modifications
    @item.update(item_params)
    price = params[:item][:price].to_f * 100
    @item.update(price: price)
    if @item.save
      redirect_to items_edit_index_path, notice: "Item Updated"
    else
      render :edit
    end
  end

  def remove_modifications
    modifications = params[:item][:modification_ids]
    modifications.delete("")
    item = params[:item][:item_id]
    modifications.each do |m|
      @modification_option = ModificationOption.find_by_item_id_and_modification_id(item, m)
      @modification_option.destroy
    end
    redirect_to items_edit_index_path, notice: "Modifications Removed"
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to items_edit_index_path, notice: "Item Deleted"
  end

  def item_params
    params.require(:item).permit(:name, :price, :restaurant_id)
  end
end

app/views/items/edit.html.erb
<div class="row">
  <div class="columns small-6">
    <h4>Edit Item</h4>
    <%= simple_form_for @item do |f| %>
      <%= f.input :name %>
      <% price = (@item.price / 100.00) %>
      <%= f.input :price, input_html: { value: "#{sprintf('%.2f', price)}" } %>
      <%= f.button :submit, "Update", class: "expand" %>
    <% end %>
    <%= button_to "Delete", item_path(@item), method: :delete, class: "button alert expand" %>
  </div>
  <div class="columns small-6">
    <h4>Remove Modifications</h4>
    <%= form_for @item,  url: { action: "remove_modifications" }, html: { method: :post } do |f| %>
      <div class="field">
        <%= f.label :modification, "Modifications" %>
        <%= f.collection_check_boxes :modification_ids, @options, :id, :name, checked:[] %>
      </div>
        <%= f.hidden_field :item_id, value: @item.id %>
      <div class="actions">
        <%= f.submit "Remove Options", class: "button expand" %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/edit_index.html.erb
<div class="row">
  <div class="columns small-12">
    <% @items.each do |i| %>
      <%= link_to "#{i.name}", edit_item_path(i) %><br>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="row">
  <div id="buttons" class="columns small-12 medium-6 large-8">
    <% @items.each do |item| %>
      <%= form_for(:sale_item, url: sale_items_path(current_restaurant)) do |f| %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.submit "#{item.name}", class: "button" %>
      <% end %>
    <% end %>
  </div>

  <%= render partial: "sales/sale" %>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="columns small-12">
    <h4>New Item</h4>
    <%= simple_form_for @item do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.hidden_field :restaurant_id, value: current_restaurant.id %>
      <%= f.button :submit, "Create Item", class: "expand" %>
    <% end %>
  </div>
</div>