config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/manager_functions'
  get 'employees/sign_in'
  post 'employees/sign_in_employee'
  get 'restaurants/sign_in'
  post 'restaurants/sign_in_restaurant'
  get 'employees/sign_out'
  get 'restaurants/sign_out'
  get '/modification_options/inverse_new'
  post '/modification_options/inverse_create'
  get 'employees/payroll'
  get 'employees/clock_in_out'
  post 'employees/clock'
  get 'items/edit_index'
  post 'sales/destroy_all'
  post 'items/remove_modifications'

  resources :restaurants, only: [:new, :create, :sign_in, :sign_in_restaurant]
  resources :items, except: [:show]
  resources :sale_items, only: [:create, :destroy, :show]
  resources :sales, only: [:update, :index, :destroy, :destroy_all]
  resources :modifications, except: [:show]
  resources :modification_options, only: [:new, :create]
  resources :sale_item_modifications, only: [:new, :create, :destroy]
  resources :employees, except: [:show]

  root 'items#index'
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :sale_items, dependent: :destroy
  belongs_to :employee
  belongs_to :restaurant
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :restaurant_exists?
  before_action :authenticate
  before_action :must_be_manager, only: [:index]

  def update
    @sale = Sale.find(params[:id])
    current_employee.update(current_sale: nil)
    print_receipt(@sale)
    redirect_to root_path
  end

  def print_receipt(sale)
    dir = "public/receipts/receipt.txt"
    File.open(dir, "w") do |f|
      f.puts Restaurant.first.name
      f.puts "-------------------------"
      sale.sale_items.each do |si|
        price = si.price / 100.00
        f.puts "#{si.name}\t#{sprintf('$%.2f', price)}"
      end
      f.puts "-------------------------"
      total = sale.total / 100.00
      f.puts "Total: #{sprintf('$%.2f', total)}"
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    current_employee.update(current_sale: nil)
    @sale.destroy
    redirect_to root_path, alert: "Transaction cancelled"
  end

  def index
    @sales = current_restaurant.sales
    @items = current_restaurant.items
  end

  def destroy_all
    current_restaurant.sales.each do |s|
      e = Employee.find(s.employee_id)
      if e.current_sale != s.id
        s.destroy
      end
    end
    redirect_to sales_path, alert: "Sales Destroyed"
  end
end

app/views/sales/_sale.html.erb
<% unless @sale.sale_items.empty? %>
  <div class="columns small-12 medium-6 large-4 panel callout radius">
    <% @sale.sale_items.each do |s_item| %>
      <div><%= link_to s_item.name, sale_item_path(s_item) %> <%= link_to "X", sale_item_path(s_item), method: :delete %>
        <% price = s_item.price / 100.00 %>
        <div class="price"><%= "#{sprintf('$%.2f', price)}" %></div>
        <ul>
          <% s_item.sale_item_modifications.each do |sim| %>
            <li><% unless sim.current_count == 1 %>
              <%= sim.current_count %>
            <% end %>
            <%= sim.modification.name %> <%= link_to "x", sale_item_modification_path(sim), method: :delete %>
            <% sim_price = (sim.modification.price / 100.00) * sim.current_count %>
            <% if sim_price > 0 %>
              <span class="price"><%= "#{sprintf('$%.2f', sim_price)}" %></span>
            <% end %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% total_price = @sale.total / 100.00 %>
    <p class="total price">Total: <%= "#{sprintf('$%.2f', total_price)}" %></p>
    <div id="hidden_total"><%= @sale.total %></div>
    <%= button_to "Cash Out", sale_path(@sale), method: :patch, id: 'cash_out', class: "button expand" %>
    <%= button_to "Cancel", sale_path(@sale), method: :delete, class: "button alert expand" %>
  </div>
<% end %>

app/views/sales/index.html.erb
<div class="row">
  <div class="columns small-12">
    <h4>Profits</h4>
    <% sum = 0 %>
    <% @sales.each do |s| %>
      <% sum += s.total  %>
    <% end %>
    <p>Total: <%= "#{sprintf('$%.2f', sum / 100.00)}"%></p>
    <% @items.each do |i| %>
      <p><%= i.name %>: <%= calculate_total_sold(i) %> sold, <%= sprintf('$%.2f', calculate_profit(i) / 100.00) %></p>
    <% end %>
    <%= button_to "Clear Data", sales_destroy_all_path, class: "button alert", method: :post %>
    <div id="one-item"></div>
  </div>
</div>

<%= content_for :extra_footer do %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script>
var today = new Date();
$(function () {
  $('#one-item').highcharts({
    title: {
      text: "Item"
    },

    xAxis: {
      type: 'datetime'
    },

    yAxis: {
      title: {
        text: "Number Sold"
      }
    },

    series: [
    <% current_restaurant.items.each do |i| %>
    {
      name: "<%= i.name %>",
      data: <%= get_sold_by_date(i) %>,
      pointInterval: 24 * 3600000,
      pointStart: today-1000*60*60*24*7
    },
    <% end %>
    ]
  });
});
</script>
<% end %>