config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/manager_functions'
  get 'employees/sign_in'
  post 'employees/sign_in_employee'
  get 'restaurants/sign_in'
  post 'restaurants/sign_in_restaurant'
  get 'employees/sign_out'
  get 'restaurants/sign_out'
  get '/modification_options/inverse_new'
  post '/modification_options/inverse_create'
  get 'employees/payroll'
  get 'employees/clock_in_out'
  post 'employees/clock'
  get 'items/edit_index'
  post 'sales/destroy_all'
  post 'items/remove_modifications'

  resources :restaurants, only: [:new, :create, :sign_in, :sign_in_restaurant]
  resources :items, except: [:show]
  resources :sale_items, only: [:create, :destroy, :show]
  resources :sales, only: [:update, :index, :destroy, :destroy_all]
  resources :modifications, except: [:show]
  resources :modification_options, only: [:new, :create]
  resources :sale_item_modifications, only: [:new, :create, :destroy]
  resources :employees, except: [:show]

  root 'items#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CashRegister</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar" data-topbar>
  <section class="top-bar-section">
  <ul class="title-area">
    <li class="name has-dropdown not-click">
      <% if current_restaurant %>
        <h1>
          <%= link_to current_restaurant.name, root_path %>
        </h1>
        <ul class="dropdown">
          <li><%= link_to "Sign Out Restaurant", restaurants_sign_out_path %></li>
        </ul>
      <% end %>
    </li>
    <li class="divider"></li>
    <li><%= link_to "Main", root_path %>
  </ul>
  </section>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <% if current_employee %>
        <li class="has-dropdown not-click">
          <% if current_employee.current_shift %>
            <% clocked_in = "Clocked in" %>
          <% else %>
            <% clocked_in = "Not clocked in" %>
          <% end %>
          <a href="#">
            <%= "Signed in as #{current_employee.name}, #{clocked_in}" %>
          </a>
          <ul class="dropdown">
            <li><%= link_to "Clock In/Out", employees_clock_in_out_path %></li>
            <li><%= link_to "Sign Out", employees_sign_out_path %></li>
          </ul>
        </li>
      <% end %>
      <% if current_employee %>
        <% if current_employee.status == "Manager" %>
          <li class="divider"></li>
          <li><%= link_to "Manager Functions", static_pages_manager_functions_path %></li>
        <% end %>
      <% end %>
    </ul>
  </section>
</nav>

<%- flash.each do |key, value| -%>
  <% if key == "notice" %>
    <div class="alert-box success" data-alert>
      <%= value %>
    </div>
  <% else %>
    <div class="alert-box alert" data-alert>
      <%= value %>
    </div>
  <% end %>
<%- end -%>

<div class="container">
  <%= yield %>
</div>

<%= javascript_include_tag 'application' %>
<%= javascript_tag do %>
$(function(){
  $(document).foundation();
});
<% end %>
<%= yield :extra_footer %>

</body>
</html>